import React from 'react';

export type ResumeProps = {
  user: any;
  skills: any[];
  roadmaps: any[];
  chapters: any[];
  projects: any[]; 
};

export const ResumeDocument = React.forwardRef<HTMLDivElement, ResumeProps>((props, ref) => {
  const { user, skills, roadmaps, chapters, projects } = props;

  return (
    <div ref={ref} className="bg-white text-black p-10 mx-auto w-[210mm] min-h-[297mm] shadow-none font-sans">
      
      {/* header */}
      <div className="border-b-2 border-gray-800 pb-4 mb-6">
        <h1 className="text-7xl text-center font-bold uppercase tracking-wider">
            {user?.username || user?.full_name || "Username"}
        </h1>
        <p className="text-gray-600 text-center mt-1 text-2xl">
            {user?.email || "email@example.com"} 
            <span className="mx-2">|</span> 
            <span className="capitalize">{user?.role || "Learner"}</span>
        </p>
      </div>

      {/* skills */}
      {skills && skills.length > 0 && (
        <div className="mb-8">
          <h3 className="text-2xl font-bold uppercase border-b border-gray-300 mb-3 pb-1">Skills</h3>
          <div className="flex flex-wrap gap-2">
            {skills.map((skill: any, index: number) => (
              <span key={index} className="px-3 py-1 rounded text-sm font-semibold">
                - {typeof skill === 'string' ? skill : skill.name}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* project submitted */}
        <div className="mb-8">
          <h3 className="text-2xl font-bold uppercase border-b border-gray-300 mb-3 pb-1">
            Projects Submitted
          </h3>
        {projects && projects.length > 0 ? (
          <div className="space-y-4">
            {projects.slice(0, 8).map((proj: any, index: number) => (
                <div key={index} className="flex justify-between items-start">
                    <div>
                        <h4 className="font-semibold text-md text-black">- {proj.title}</h4>
                        <p className="text-sm text-gray-600 italic mt-0.5">
                            {proj.description}
                        </p>
                    </div>
                </div>
            ))}
          </div>
        
      ) : (
        <p className="text-sm text-gray-500 italic mt-2">No projects submitted.</p>
      )}
      </div>

      {/* roadmap */}
      
        <div className="mb-8">
          <h3 className="text-2xl font-bold uppercase border-b border-gray-300 mb-3 pb-1">
            Roadmaps Completed
          </h3>
        {roadmaps && roadmaps.length > 0 ? (
          <div className="space-y-4">
            {roadmaps.slice(0, 10).map((map: any, index: number) => (
                <div key={index} className="grid grid-cols-2 gap-x-8 gap-y-4">
                  <h4 className="font-semibold text-md text-black leading-tight">- {map.title}</h4>
                </div>
            ))}
          </div>
        ): (
          <p className="text-sm text-gray-500 italic mt-2">No roadmaps completed.</p>
        )}
      </div>
      {/* chapter completed */}
      <div className="mb-8">
        <h3 className="text-2xl font-bold uppercase border-b border-gray-300 mb-3 pb-1">
          Chapters Completed
        </h3>
        {chapters && chapters.length > 0 ? (
          <div className="grid grid-cols-2 gap-x-8 gap-y-4">
            {chapters.slice(0, 12).map((chap: any, index: number) => (
                <div key={index} className="flex justify-between items-start">
                  <h4 className="font-semibold text-md text-black leading-tight">- {chap.title}</h4>
                </div>
            ))}
          </div>
        ) : (
            <p className="text-sm text-gray-500 italic mt-2">No chapters completed.</p>
        )}
      </div>

      {/* footer */}
      <div className="mt-auto pt-10 border-t border-gray-200 text-center text-xs text-gray-400">
        Generated by UpCode
      </div>
    </div>
  );
});

ResumeDocument.displayName = "ResumeDocument";