import React from "react";
import SearchBar from "@/component/searchBar";
import { useState } from "react";
import RadioGroup from "../../component/projects/radioGroup.tsx";
import type { ProjectType } from "../../store/projectsSlice.ts";
import { useSelector } from "react-redux";
import { categoryList } from "@/lib/types.ts";
import { useNavigate } from "react-router";
import ProjectCard from "../../component/projects/projectCard.tsx";
import SubmissionCard from "@/component/projects/submissionCard.tsx";


export const MyProjects: React.FC = () => {
  const navigate = useNavigate();
  const selections = ["All", ...categoryList];
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState(selections[0]);
  const [submissionType, setSubmissionType] = useState<"Projects" | "Submissions">("Projects");
  const userId = useSelector((state: any) => state.profile.userId);
  const projects = useSelector((state: any) => state.projects.projectsList)
    .filter((project: ProjectType) => project.creatorId === userId);
  const submissions = useSelector((state: any) => state.submissions.submissionsList)
    .filter((submission: any) => submission.creatorId === userId);
  function handleCategoryChange(value: string) {
    setCategory(value);
  }

  function navigateToDetails(path: string, destId: number) {
    navigate(`/${path}/${destId}`);
  }
  
  const hasProjectsToShow = submissionType === "Projects" && (category === "All" || projects.some((project: ProjectType) => project.category === category));
  // The logic below was generated by AI. To be verified later
  const hasSolutionsToShow = submissionType === "Submissions" && (category === "All" || submissions.some((submission: any) => {
    const project = projects.some((proj: ProjectType) => proj.projectId === submission.projectId);
    return project && (category === "All" || project.category === category);
  }));
  return (
    <div className="pt-6 px-3 w-full mx-auto flex flex-col">
      <div className="sticky">
        <h1 className="text-3xl font-bold text-white">My Projects & Submissions</h1>
        <div className="w-[80%] mx-auto my-5">
          <SearchBar
            placeholder="Search projects by title or description"
            query={query}
            setQuery={setQuery}
            className="mt-4"
          />
        </div>
        <div className="mx-auto">
          <RadioGroup
            options={["Projects", "Submissions"]}
            selected={submissionType}
            onClick={(value) => setSubmissionType(value as "Projects" | "Submissions")}
            isHorizontal={true}
            className="w-[50%] mx-auto mb-5"
            // rounded upper borders
            buttonClassName="rounded-t-lg"
          />
        </div>
      </div>
      <div className="w-full fixed bottom-0 top-70 px-10 grid grid-cols-[200px_1fr] gap-10">
        <RadioGroup
          options={selections}
          selected={category}
          onClick={handleCategoryChange}
          isHorizontal={false}
          className="w-50"
        />
        {
          submissionType === "Projects" && (hasProjectsToShow ?
            <div className="pt-5 grid grid-cols-3 gap-2 scroll-auto">
              {projects.map((project: ProjectType) => {
                if (category !== "All" && project.category !== category) return null;
                if (query && !project.title.toLowerCase().includes(query.toLowerCase()) &&
                  !project.shortDescription.toLowerCase().includes(query.toLowerCase())) {
                  return null;
                }
                return (
                  <ProjectCard key={project.projectId} project={project}
                    onClick={() => navigateToDetails("project", project.projectId)}
                  />
                );
              })}
            </div> :
            <p className="text-white font-light text-4xl text-center mt-10">No {category === "All" ? "" : category} projects found</p>
          )
        }
        {/* The part below was generated by AI. Logic to be verified later */}
        {
          submissionType === "Submissions" && (hasSolutionsToShow ?
            <div className="pt-5 flex flex-col gap-2">
              {submissions.map((submission: any) => {
                const project = projects.find((proj: ProjectType) => proj.projectId === submission.projectId);
                if (!project) return null;
                if (category !== "All" && project.category !== category) return null;
                if (query && !submission.title.toLowerCase().includes(query.toLowerCase()) &&
                  !project.title.toLowerCase().includes(query.toLowerCase()) &&
                  !project.shortDescription.toLowerCase().includes(query.toLowerCase())) {
                  return null;
                }
                return (
                  <SubmissionCard key={submission.submissionId} 
                    creator={submission.creator}
                    date={submission.postedOn}
                    title={submission.title}
                    tag={project.category}
                    onClick={() => navigateToDetails("project/submission", submission.submissionId)}
                  />
                );
              }
              )}
            </div> :
            <p className="text-white font-light text-4xl text-center mt-10">No {category === "All" ? "" : category} submissions found</p>
          )
        }
      </div>
    </div>
  );
};