import type{ RoadmapItemCardProps} from "./component/cardDetail";
import javaImage from "./assets/image/java_intro.jpg";
import pythonImage from "./assets/image/python_intro.jpg";

export const roadmapData: RoadmapItemCardProps[] = [
  {
    id: 100001,
    slug: "java-fundamentals",
    creator: 1,
    imageSrc: javaImage,
    title: "Java Fundamentals",
    description: "Learn the basics of Java programming language.",
    date: "2025-10-20",
    tags: [
      { type: "Difficulty", label: "Beginner" },
      { type: "Category", label: "Java" },
      { type: "Prerequisite", label: "None" },
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "Python" },
      { type: "Prerequisite", label: "Basic Programming" },
    ],
  },
  {
    id: 100002,
    slug: "python-basics",
    creator: 2,
    imageSrc: pythonImage,
    title: "Python Basics",
    description: "Learn the basics of Python programming language.",
    date: "2025-11-05",
    tags: [
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "Python" },
      { type: "Prerequisite", label: "Basic Programming" },
    ],
  },
  {
    id: 100003,
    slug: "javascript-essentials",
    creator: 3,
    imageSrc: pythonImage,
    title: "JavaScript Essentials",
    description: "Learn the essentials of JavaScript programming language.",
    date: "2025-11-15",
    tags: [
      { type: "Difficulty", label: "Beginner" },
      { type: "Category", label: "JavaScript" },
      { type: "Prerequisite", label: "None" },
    ],
  },
  {
    id: 100004,
    slug: "react-for-beginners",
    creator: 4,
    imageSrc: pythonImage,
    title: "React for Beginners",
    description: "Learn the basics of React framework.",
    date: "2025-11-25",
    tags: [
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "React" },
      { type: "Prerequisite", label: "JavaScript Basics" },
    ],
  },
  {
    id: 100005,
    slug: "nodejs-fundamentals",
    creator: 5,
    imageSrc: pythonImage,
    title: "Node.js Fundamentals",
    description: "Learn the fundamentals of Node.js runtime environment.",
    date: "2025-12-05",
    tags: [
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "Node.js" },
      { type: "Prerequisite", label: "JavaScript Basics" },
    ],
  },
  {
    id: 100006,
    slug: "sql-basics",
    creator: 6,
    imageSrc: pythonImage,
    title: "SQL Basics",
    description: "Learn the basics of SQL database language.",
    date: "2025-12-15",
    tags: [
      { type: "Difficulty", label: "Beginner" },
      { type: "Category", label: "Database" },
      { type: "Prerequisite", label: "None" },
    ],
  },
  {
    id: 100007,
    slug: "html-css-fundamentals",
    creator: 7,
    imageSrc: javaImage,
    title: "HTML & CSS Fundamentals",
    description: "Learn the basics of HTML and CSS for web development.",
    date: "2025-12-20",
    tags: [
      { type: "Difficulty", label: "Beginner" },
      { type: "Category", label: "Web Development" },
      { type: "Prerequisite", label: "None" },
    ],
  },
  {
    id: 100008,
    slug: "typescript-basics",
    creator: 8,
    imageSrc: javaImage,
    title: "TypeScript Basics",
    description: "Learn the basics of TypeScript programming language.",
    date: "2026-01-05",
    tags: [
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "TypeScript" },
      { type: "Prerequisite", label: "JavaScript Basics" },
    ],
  },
  {
    id: 100009,
    slug: "angular-fundamentals",
    creator: 9,
    imageSrc: javaImage,
    title: "Angular Fundamentals",
    description: "Learn the fundamentals of Angular framework.",
    date: "2026-01-15",
    tags: [
      { type: "Difficulty", label: "Advanced" },
      { type: "Category", label: "Angular" },
      { type: "Prerequisite", label: "TypeScript Basics" },
    ],
  },
  {
    id: 100010,
    slug: "python-advanced-concepts",
    creator: 10,
    imageSrc: pythonImage,
    title: "Python Advanced Concepts",
    description: "Explore advanced concepts in Python programming.",
    date: "2026-01-25",
    tags: [
      { type: "Difficulty", label: "Advanced" },
      { type: "Category", label: "Python" },
      { type: "Prerequisite", label: "Python Basics" },
    ],
  },
  {
    id: 100011,
    slug: "java-advanced-topics",
    creator: 11,
    imageSrc: javaImage,
    title: "Java Advanced Topics",
    description: "Explore advanced topics in Java programming.",
    date: "2026-02-05",
    tags: [
      { type: "Difficulty", label: "Advanced" },
      { type: "Category", label: "Java" },
      { type: "Prerequisite", label: "Java Fundamentals" },
    ],
  },
  {
    id: 100012,
    slug: "react-advanced-patterns",
    creator: 12,
    imageSrc: javaImage,
    title: "React Advanced Patterns",
    description: "Explore advanced patterns in React development.",
    date: "2026-02-15",
    tags: [
      { type: "Difficulty", label: "Advanced" },
      { type: "Category", label: "React" },
      { type: "Prerequisite", label: "React for Beginners" },
    ],
  },
];
