import type{ RoadmapItemCardProps} from "./component/roadmaps/cardDetail";
import javaImage from "./assets/image/java_intro.jpg";
import pythonImage from "./assets/image/python_intro.jpg";
import type { PillarCardProps } from "./component/roadmaps/pillarCard";

export const roadmapData: RoadmapItemCardProps[] = [
  {
    id: 100001,
    slug: "java-fundamentals",
    creator: 1,
    imageSrc: javaImage,
    title: "Java Fundamentals",
    description: "The Java Fundamentals roadmap is designed to build a strong foundation in the Java programming language. It starts with essential topics such as data types, control flow, arrays, and Object-Oriented Programming (OOP) concepts like classes, objects, inheritance, and polymorphism. You will also learn how to work with the Java Collections Framework, handle exceptions, and use Java’s functional features like lambda expressions and the Stream API. This roadmap prepares learners for real-world development and serves as a prerequisite for more advanced Java frameworks like Spring Boot.",
    createdDate: "2025-10-20",
    modifiedDate: "2025-10-20",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Beginner" },
      { type: "Category", label: "Java" },
      { type: "Prerequisite", label: "None" },
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "Python" },
      { type: "Prerequisite", label: "Basic Programming" },
    ],
  },
  {
    id: 100002,
    slug: "python-basics",
    creator: 2,
    imageSrc: pythonImage,
    title: "Python Basics",
    description: "Python Basics introduces new learners to one of the most popular and beginner-friendly programming languages. This roadmap covers variables, loops, conditions, functions, and basic data structures such as lists and dictionaries. You will also explore simple file handling, modules, and basic problem-solving techniques. The goal is to help beginners write clean and readable Python scripts while building confidence to continue toward intermediate Python topics or apply Python in fields like data analytics, automation, and AI.",
    createdDate: "2025-11-05",
    modifiedDate: "2025-11-05",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "Python" },
      { type: "Prerequisite", label: "Basic Programming" },
    ],
  },
  {
    id: 100003,
    slug: "javascript-essentials",
    creator: 3,
    imageSrc: pythonImage,
    title: "JavaScript Essentials",
    description: "JavaScript Essentials provides a clear path for mastering the core features of JavaScript, the language of the web. This roadmap includes topics such as variables, functions, loops, arrays, objects, and basic DOM manipulation. You will also learn how JavaScript runs in the browser, how events work, and how to interact with HTML and CSS. These fundamentals form the base required for front-end frameworks like React, Angular, and Vue.",
    createdDate: "2025-08-15",
    modifiedDate: "2025-11-15",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Beginner" },
      { type: "Category", label: "JavaScript" },
      { type: "Prerequisite", label: "None" },
    ],
  },
  {
    id: 100004,
    slug: "react-for-beginners",
    creator: 4,
    imageSrc: pythonImage,
    title: "React for Beginners",
    description: "This roadmap introduces the basics of React, one of the most in-demand front-end frameworks. You will learn how to create components, manage state, handle props, and work with React Hooks such as useState and useEffect. The roadmap also covers JSX, component trees, and simple API fetching. By the end, you will understand how to build interactive and reusable UI components — an essential skill for modern web development.",
    createdDate: "2025-09-25",
    modifiedDate: "2025-11-25",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "React" },
      { type: "Prerequisite", label: "JavaScript Basics" },
    ],
  },
  {
    id: 100005,
    slug: "nodejs-fundamentals",
    creator: 5,
    imageSrc: pythonImage,
    title: "Node.js Fundamentals",
    description: "Node.js Fundamentals guides you into the world of backend JavaScript development. You will learn how Node.js works, how to use built-in modules, and how to create simple servers. The roadmap also covers asynchronous programming, callbacks, promises, and using npm packages. By understanding the Node.js runtime environment and event loop, you will be prepared to build APIs or move into full-stack development using frameworks like Express.js.",
    createdDate: "2025-11-09",
    modifiedDate: "2025-12-05",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "Node.js" },
      { type: "Prerequisite", label: "JavaScript Basics" },
    ],
  },
  {
    id: 100006,
    slug: "sql-basics",
    creator: 6,
    imageSrc: pythonImage,
    title: "SQL Basics",
    description: "SQL Basics provides a foundational understanding of relational databases and the SQL language. You will learn how to create, read, update, and delete data using SQL queries. The roadmap covers essential concepts such as database design, normalization, joins, and indexing. By mastering SQL, you will be equipped to work with popular database systems like MySQL, PostgreSQL, and SQLite, which are crucial for backend development and data management.",
    createdDate: "2025-12-15",
    modifiedDate: "2025-12-15",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Beginner" },
      { type: "Category", label: "Database" },
      { type: "Prerequisite", label: "None" },
    ],
  },
  {
    id: 100007,
    slug: "html-css-fundamentals",
    creator: 7,
    imageSrc: javaImage,
    title: "HTML & CSS Fundamentals",
    description:  "HTML & CSS Fundamentals teaches the core building blocks of web development. You will learn how to structure webpages using HTML elements such as headings, paragraphs, lists, and forms. Then, you will work with CSS to style layouts, apply colors, spacing, and responsive design. This roadmap helps beginners create clean and attractive webpages and builds the foundation needed for JavaScript and front-end frameworks.",
    createdDate: "2025-11-11",
    modifiedDate: "2025-12-20",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Beginner" },
      { type: "Category", label: "Web Development" },
      { type: "Prerequisite", label: "None" },
    ],
  },
  {
    id: 100008,
    slug: "typescript-basics",
    creator: 8,
    imageSrc: javaImage,
    title: "TypeScript Basics",
    description: "TypeScript Basics introduces the strongly typed superset of JavaScript that adds static types. You will learn about type annotations, interfaces, classes, and generics. The roadmap covers how TypeScript improves code quality and developer experience by catching errors early and enabling better tooling. By mastering TypeScript basics, you will be prepared to work on large-scale JavaScript applications and frameworks like Angular.",
    createdDate: "2025-12-05",
    modifiedDate: "2026-01-05",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Intermediate" },
      { type: "Category", label: "TypeScript" },
      { type: "Prerequisite", label: "JavaScript Basics" },
    ],
  },
  {
    id: 100009,
    slug: "angular-fundamentals",
    creator: 9,
    imageSrc: javaImage,
    title: "Angular Fundamentals",
    description: "Angular Fundamentals covers the core concepts of the Angular framework. You will learn about components, templates, data binding, directives, services, and dependency injection. The roadmap also introduces Angular CLI, routing, and forms. By mastering these fundamentals, you will be able to build dynamic single-page applications and understand the architecture of modern front-end development with Angular.",
    createdDate: "2025-01-15",
    modifiedDate: "2026-01-15",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Advanced" },
      { type: "Category", label: "Angular" },
      { type: "Prerequisite", label: "TypeScript Basics" },
    ],
  },
  {
    id: 100010,
    slug: "python-advanced-concepts",
    creator: 10,
    imageSrc: pythonImage,
    title: "Python Advanced Concepts",
    description: "Explore advanced concepts in Python programming, including decorators, generators, context managers, metaclasses, and concurrency. This roadmap helps you deepen your understanding of Python's capabilities and prepares you for complex application development and optimization.",
    createdDate: "2026-01-25",
    modifiedDate: "2026-02-25",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Advanced" },
      { type: "Category", label: "Python" },
      { type: "Prerequisite", label: "Python Basics" },
    ],
  },
  {
    id: 100011,
    slug: "java-advanced-topics",
    creator: 11,
    imageSrc: javaImage,
    title: "Java Advanced Topics",
    description: "Explore advanced topics in Java programming, including concurrency, JVM internals, garbage collection, and performance tuning. This roadmap helps you deepen your understanding of Java's capabilities and prepares you for building high-performance, scalable applications.",
    createdDate: "2026-01-05",
    modifiedDate: "2026-02-05",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Advanced" },
      { type: "Category", label: "Java" },
      { type: "Prerequisite", label: "Java Fundamentals" },
    ],
  },
  {
    id: 100012,
    slug: "react-advanced-patterns",
    creator: 12,
    imageSrc: javaImage,
    title: "React Advanced Patterns",
    description: "Explore advanced patterns in React development, including higher-order components, render props, context API, hooks, and performance optimization techniques. This roadmap helps you build scalable and maintainable React applications by mastering design patterns and best practices.",
    createdDate: "2025-02-15",
    modifiedDate: "2026-02-15",
    isFavourite: false,
    tags: [
      { type: "Difficulty", label: "Advanced" },
      { type: "Category", label: "React" },
      { type: "Prerequisite", label: "React for Beginners" },
    ],
  },
];


export const pillarsData: PillarCardProps[] = [
    {
        id: 100001,
        slug: "introduction-to-programming",
        roadmapid: 100001,
        title: "Introduction to Programming",
        description: "Learn the basics of programming, including variables, data types, and control structures.",
        modifiedDate: "2023-10-01",
        tags: [],
        order: 1,
        isViewed: false
    },
    {
        id: 100002,
        slug: "object-oriented-programming",
        roadmapid: 100001,
        title: "Object-Oriented Programming",
        description: "Understand the principles of OOP, including classes, objects, inheritance, and polymorphism.", 
        modifiedDate: "2023-10-05",
        tags: [],
        order: 2,
        isViewed: false
    },
    {   id: 100003,
        slug: "data-structures-and-algorithms",
        roadmapid: 100001,
        title: "Data Structures and Algorithms",
        description: "Explore common data structures and algorithms used in programming.",
        modifiedDate: "2023-10-10",
        tags: [],
        order: 3,
        isViewed: false
    },
    {  id: 100004,
        slug: "error-handling-and-exceptions",
        roadmapid: 100001,
        title: "Error Handling and Exceptions",
        description: "Learn how to handle errors and exceptions in your code effectively.",
        modifiedDate: "2023-10-15",
        tags: [],
        order: 4,
        isViewed: false
    },
    {  id: 100005,
        slug: "java-collections-framework",
        roadmapid: 100001, 
        title: "Java Collections Framework",
        description: "Dive into the Java Collections Framework, including lists, sets, maps, and queues.",
        modifiedDate: "2023-10-20",
        tags: [],
        order: 5,
        isViewed: false
    },
    {  id: 100006,
        slug: "functional-programming-in-python",
        roadmapid: 100002,
        title: "Functional Programming in Python",
        description: "Learn about functional programming concepts in Python, including lambda functions, map, filter, and reduce.",
        modifiedDate: "2023-11-01",
        tags: [],
        order: 1,
        isViewed: false
      },
      {
        id: 100007,
        slug: "file-handling-in-python",
        roadmapid: 100002,
        title: "File Handling in Python",
        description: "Understand how to read from and write to files using Python.",
        modifiedDate: "2023-11-05",
        tags: [],
        order: 2,
        isViewed: false
      },
      {
        id: 100008,
        slug: "modules-and-packages",
        roadmapid: 100002,
        title: "Modules and Packages",
        description: "Learn how to create and use modules and packages in Python for better code organization.",
        modifiedDate: "2023-11-10",
        tags: [],
        order: 3,
        isViewed: false
      },
      {
        id: 100009,
        slug: "error-and-exception-handling",
        roadmapid: 100002,
        title: "Error and Exception Handling",
        description: "Learn how to handle errors and exceptions in Python effectively.",
        modifiedDate: "2023-11-15",
        tags: [],
        order: 4,
        isViewed: false
      },
      {  
        id: 100010,
        slug: "working-with-databases",
        roadmapid: 100002,  
        title: "Working with Databases",
        description: "Understand how to connect to and interact with databases using Python.",
        modifiedDate: "2023-11-20",
        tags: [],
        order: 5,
        isViewed: false
      }
];