import type{ RoadmapItemCardProps} from "./component/roadmaps/roadmapCard";
import { defaultImageSrc, javaImage, pythonImage, javaScriptImage, cImage, machinelearningImage,
         devopsImage, frontendImage, backendImage, reactImage, apiImage, angularImage,
         typeScriptImage, htmlcssImage, sqlImage
 } from "./component/roadmaps/image";
import type { PillarCardProps } from "./component/roadmaps/pillarCard";
import type { LinkCardProps } from "./component/roadmaps/linkCard";

export const roadmapData: RoadmapItemCardProps[] = [
  {
    roadmapID: 100001,
    roadmapSlug: "java-fundamentals",
    creator: 100001,
    imageSrc: javaImage,
    title: "Java Fundamentals",
    description: "The Java Fundamentals roadmap is designed to build a strong foundation in the Java programming language. It starts with essential topics such as data types, control flow, arrays, and Object-Oriented Programming (OOP) concepts like classes, objects, inheritance, and polymorphism. You will also learn how to work with the Java Collections Framework, handle exceptions, and use Java’s functional features like lambda expressions and the Stream API. This roadmap prepares learners for real-world development and serves as a prerequisite for more advanced Java frameworks like Spring Boot.",
    createdDate: "2025-10-20",
    modifiedDate: "2025-10-20",
    isFavourite: false,
    
  },
  {
    roadmapID: 100002,
    roadmapSlug: "python-basics",
    creator: 100002,
    imageSrc: pythonImage,
    title: "Python Basics",
    description: "Python Basics introduces new learners to one of the most popular and beginner-friendly programming languages. This roadmap covers variables, loops, conditions, functions, and basic data structures such as lists and dictionaries. You will also explore simple file handling, modules, and basic problem-solving techniques. The goal is to help beginners write clean and readable Python scripts while building confidence to continue toward intermediate Python topics or apply Python in fields like data analytics, automation, and AI.",
    createdDate: "2025-11-05",
    modifiedDate: "2025-11-05",
    isFavourite: false,
    
  },
  {
    roadmapID: 100003,
    roadmapSlug: "javascript-essentials",
    creator: 100002,
    imageSrc: javaScriptImage,
    title: "JavaScript Essentials",
    description: "JavaScript Essentials provides a clear path for mastering the core features of JavaScript, the language of the web. This roadmap includes topics such as variables, functions, loops, arrays, objects, and basic DOM manipulation. You will also learn how JavaScript runs in the browser, how events work, and how to interact with HTML and CSS. These fundamentals form the base required for front-end frameworks like React, Angular, and Vue.",
    createdDate: "2025-08-15",
    modifiedDate: "2025-11-15",
    isFavourite: false,
    
  },
  {
    roadmapID: 100004,
    roadmapSlug: "react-for-beginners",
    creator: 100003,
    imageSrc: reactImage,
    title: "React for Beginners",
    description: "This roadmap introduces the basics of React, one of the most in-demand front-end frameworks. You will learn how to create components, manage state, handle props, and work with React Hooks such as useState and useEffect. The roadmap also covers JSX, component trees, and simple API fetching. By the end, you will understand how to build interactive and reusable UI components — an essential skill for modern web development.",
    createdDate: "2025-09-25",
    modifiedDate: "2025-11-25",
    isFavourite: false,
    
  },
  {
    roadmapID: 100005,
    roadmapSlug: "nodejs-fundamentals",
    creator: 100001,
    imageSrc: defaultImageSrc,
    title: "Node.js Fundamentals",
    description: "Node.js Fundamentals guides you into the world of backend JavaScript development. You will learn how Node.js works, how to use built-in modules, and how to create simple servers. The roadmap also covers asynchronous programming, callbacks, promises, and using npm packages. By understanding the Node.js runtime environment and event loop, you will be prepared to build APIs or move into full-stack development using frameworks like Express.js.",
    createdDate: "2025-11-09",
    modifiedDate: "2025-12-05",
    isFavourite: false,
    
  },
  {
    roadmapID: 100006,
    roadmapSlug: "sql-basics",
    creator: 100007,
    imageSrc: sqlImage,
    title: "SQL Basics",
    description: "SQL Basics provides a foundational understanding of relational databases and the SQL language. You will learn how to create, read, update, and delete data using SQL queries. The roadmap covers essential concepts such as database design, normalization, joins, and indexing. By mastering SQL, you will be equipped to work with popular database systems like MySQL, PostgreSQL, and SQLite, which are crucial for backend development and data management.",
    createdDate: "2025-12-15",
    modifiedDate: "2025-12-15",
    isFavourite: false,
    
  },
  {
    roadmapID: 100007,
    roadmapSlug: "html-css-fundamentals",
    creator: 100007,
    imageSrc: htmlcssImage,
    title: "HTML & CSS Fundamentals",
    description:  "HTML & CSS Fundamentals teaches the core building blocks of web development. You will learn how to structure webpages using HTML elements such as headings, paragraphs, lists, and forms. Then, you will work with CSS to style layouts, apply colors, spacing, and responsive design. This roadmap helps beginners create clean and attractive webpages and builds the foundation needed for JavaScript and front-end frameworks.",
    createdDate: "2025-11-11",
    modifiedDate: "2025-12-20",
    isFavourite: false,
    
  },
  {
    roadmapID: 100008,
    roadmapSlug: "typescript-basics",
    creator: 100001,
    imageSrc: typeScriptImage,
    title: "TypeScript Basics",
    description: "TypeScript Basics introduces the strongly typed superset of JavaScript that adds static types. You will learn about type annotations, interfaces, classes, and generics. The roadmap covers how TypeScript improves code quality and developer experience by catching errors early and enabling better tooling. By mastering TypeScript basics, you will be prepared to work on large-scale JavaScript applications and frameworks like Angular.",
    createdDate: "2025-12-05",
    modifiedDate: "2026-01-05",
    isFavourite: false,
    
  },
  {
    roadmapID: 100009,
    roadmapSlug: "angular-fundamentals",
    creator: 100002,
    imageSrc: angularImage,
    title: "Angular Fundamentals",
    description: "Angular Fundamentals covers the core concepts of the Angular framework. You will learn about components, templates, data binding, directives, services, and dependency injection. The roadmap also introduces Angular CLI, routing, and forms. By mastering these fundamentals, you will be able to build dynamic single-page applications and understand the architecture of modern front-end development with Angular.",
    createdDate: "2025-01-15",
    modifiedDate: "2026-01-15",
    isFavourite: false,
    
  },
  {
    roadmapID: 100010,
    roadmapSlug: "python-advanced-concepts",
    creator: 100004,
    imageSrc: pythonImage,
    title: "Python Advanced Concepts",
    description: "Explore advanced concepts in Python programming, including decorators, generators, context managers, metaclasses, and concurrency. This roadmap helps you deepen your understanding of Python's capabilities and prepares you for complex application development and optimization.",
    createdDate: "2026-01-25",
    modifiedDate: "2026-02-25",
    isFavourite: false,
    
  },
  {
    roadmapID: 100011,
    roadmapSlug: "java-advanced-topics",
    creator: 100001,
    imageSrc: javaImage,
    title: "Java Advanced Topics",
    description: "Explore advanced topics in Java programming, including concurrency, JVM internals, garbage collection, and performance tuning. This roadmap helps you deepen your understanding of Java's capabilities and prepares you for building high-performance, scalable applications.",
    createdDate: "2026-01-05",
    modifiedDate: "2026-02-05",
    isFavourite: false,
    
  },
  {
    roadmapID: 100012,
    roadmapSlug: "react-advanced-patterns",
    creator: 100002,
    imageSrc: reactImage,
    title: "React Advanced Patterns",
    description: "Explore advanced patterns in React development, including higher-order components, render props, context API, hooks, and performance optimization techniques. This roadmap helps you build scalable and maintainable React applications by mastering design patterns and best practices.",
    createdDate: "2025-02-15",
    modifiedDate: "2026-02-15",
    isFavourite: false,
    
  },
  {
    roadmapID: 100013,
    roadmapSlug: "api-design-and-development",
    creator: 100003,
    imageSrc: apiImage,
    title: "API Design and Development",
    description: "Master the principles of designing, developing, and deploying robust APIs. Topics include RESTful design, GraphQL fundamentals, authentication (OAuth, JWT), API documentation (Swagger/OpenAPI), and performance testing.",
    createdDate: "2025-03-01",
    modifiedDate: "2026-03-01",
    isFavourite: false,
  },
  {
    roadmapID: 100014,
    roadmapSlug: "modern-frontend-development",
    creator: 100004,
    imageSrc: frontendImage,
    title: "Modern Frontend Development",
    description: "A comprehensive path covering HTML5, CSS3 (Flexbox/Grid), advanced JavaScript (ES6+), and popular frameworks like Vue.js and Svelte. Focus on responsive design, state management, and build tools (Webpack/Vite).",
    createdDate: "2025-04-10",
    modifiedDate: "2026-04-10",
    isFavourite: false,
  },
  {
    roadmapID: 100015,
    roadmapSlug: "scalable-backend-engineering",
    creator: 100005,
    imageSrc: backendImage,
    title: "Scalable Backend Engineering",
    description: "Learn to build high-performance, scalable servers using languages like Node.js, Go, or Python (Django/Flask). Includes database management (SQL/NoSQL), microservices architecture, caching strategies, and security implementation.",
    createdDate: "2025-05-20",
    modifiedDate: "2026-05-20",
    isFavourite: false,
  },
  {
    roadmapID: 100016,
    roadmapSlug: "devops-fundamentals-and-ci-cd",
    creator: 100006,
    imageSrc: devopsImage,
    title: "DevOps Fundamentals and CI/CD",
    description: "Master the DevOps toolchain, focusing on automation, infrastructure as code (Terraform), containerization (Docker, Kubernetes), and building continuous integration/continuous delivery (CI/CD) pipelines (Jenkins/GitLab CI).",
    createdDate: "2025-06-05",
    modifiedDate: "2026-06-05",
    isFavourite: false,
  },
  {
    roadmapID: 100017,
    roadmapSlug: "machine-learning-engineering",
    creator: 100007,
    imageSrc: machinelearningImage,
    title: "Machine Learning Engineering",
    description: "A deep dive into model development, training, and deployment. Covers core algorithms, data preprocessing, MLOps, cloud platforms (AWS Sagemaker/Azure ML), and performance optimization for production environments.",
    createdDate: "2025-07-12",
    modifiedDate: "2026-07-12",
    isFavourite: false,
  },
  {
    roadmapID: 100018,
    roadmapSlug: "modern-c++",
    creator: 100008,
    imageSrc: cImage,
    title: "Modern C++ Programming",
    description: "Focus on C++17 and C++20 features, object-oriented programming, standard template library (STL), memory management, multithreading, and best practices for developing high-performance, low-latency applications.",
    createdDate: "2025-08-25",
    modifiedDate: "2026-08-25",
    isFavourite: false,
},
];


export const pillarsData: PillarCardProps[] = [
    {
        chapterID: 100001,
        chapterSlug: "introduction-to-programming",
        roadmapID: 100001,
        title: "Introduction to Programming",
        description: "Learn the basics of programming, including variables, data types, and control structures.",
        modifiedDate: "2023-10-01",
        difficulty: "Intermediate",
        category: "Java",
        prerequisite: "None",
        order: 1,
        isViewed: false
    },
    {
        chapterID: 100002,
        chapterSlug: "object-oriented-programming",
        roadmapID: 100001,
        title: "Object-Oriented Programming",
        description: "Understand the principles of OOP, including classes, objects, inheritance, and polymorphism.", 
        modifiedDate: "2023-10-05",
        difficulty: "Advanced",
        category: "OOP",
        prerequisite: "None",
        order: 2,
        isViewed: false
    },
    {   chapterID: 100003,
        chapterSlug: "data-structures-and-algorithms",
        roadmapID: 100001,
        title: "Data Structures and Algorithms",
        description: "Explore common data structures and algorithms used in programming.",
        modifiedDate: "2023-10-10",
        difficulty: "Advanced",
        category: "OOP",
        prerequisite: "None",
        order: 3,
        isViewed: false
    },
    {  chapterID: 100004,
        chapterSlug: "error-handling-and-exceptions",
        roadmapID: 100001,
        title: "Error Handling and Exceptions",
        description: "Learn how to handle errors and exceptions in your code effectively.",
        modifiedDate: "2023-10-15",
        difficulty: "Advanced",
        category: "OOP",
        prerequisite: "None",
        order: 4,
        isViewed: false
    },
    {  chapterID: 100005,
        chapterSlug: "java-collections-framework",
        roadmapID: 100001, 
        title: "Java Collections Framework",
        description: "Dive into the Java Collections Framework, including lists, sets, maps, and queues.",
        modifiedDate: "2023-10-20",
        difficulty: "Intermediate",
        category: "Java",
        prerequisite: "None",
        order: 5,
        isViewed: false
    },
    {  chapterID: 100006,
        chapterSlug: "functional-programming-in-python",
        roadmapID: 100002,
        title: "Functional Programming in Python",
        description: "Learn about functional programming concepts in Python, including lambda functions, map, filter, and reduce.",
        modifiedDate: "2023-11-01",
        difficulty: "Intermediate",
        category: "OOP",
        prerequisite: "None",
        order: 1,
        isViewed: false
      },
      {
        chapterID: 100007,
        chapterSlug: "file-handling-in-python",
        roadmapID: 100002,
        title: "File Handling in Python",
        description: "Understand how to read from and write to files using Python.",
        modifiedDate: "2023-11-05",
        difficulty: "Beginner",
        category: "OOP",
        prerequisite: "None",
        order: 2,
        isViewed: false
      },
      {
        chapterID: 100008,
        chapterSlug: "modules-and-packages",
        roadmapID: 100002,
        title: "Modules and Packages",
        description: "Learn how to create and use modules and packages in Python for better code organization.",
        modifiedDate: "2023-11-10",
        difficulty: "Advanced",
        category: "OOP",
        prerequisite: "Python",
        order: 3,
        isViewed: false
      },
      {
        chapterID: 100009,
        chapterSlug: "error-and-exception-handling",
        roadmapID: 100002,
        title: "Error and Exception Handling",
        description: "Learn how to handle errors and exceptions in Python effectively.",
        modifiedDate: "2023-11-15",
        difficulty: "Beginner",
        category: "OOP",
        prerequisite: "Python",
        order: 4,
        isViewed: false
      },
      {  
        chapterID: 100010,
        chapterSlug: "working-with-databases",
        roadmapID: 100002,  
        title: "Working with Databases",
        description: "Understand how to connect to and interact with databases using Python.",
        modifiedDate: "2023-11-20",
        difficulty: "Advanced",
        category: "OOP",
        prerequisite: "None",
        order: 5,
        isViewed: false
      },
      {
        chapterID: 100011,
        chapterSlug: "java-stream-api",
        roadmapID: 100001,
        title: "Java Stream API",
        description: "Learn how to use Java Stream API for functional-style operations on collections.",
        modifiedDate: "2023-10-25",
        difficulty: "Intermediate",
        category: "Java",
        prerequisite: "None",
        order: 6,
        isViewed: false
      },
      {
        chapterID: 100012,
        chapterSlug: "java-lambda-expressions",
        roadmapID: 100001,
        title: "Lambda Expressions",
        description: "Understand lambda expressions and how they introduce functional programming in Java.",
        modifiedDate: "2023-10-30",
        difficulty: "Advanced",
        category: "Java",
        prerequisite: "None",
        order: 7,
        isViewed: false
      },
      {
        chapterID: 100013,
        chapterSlug: "python-data-structures",
        roadmapID: 100002,
        title: "Python Data Structures",
        description: "Learn about Python lists, dictionaries, tuples, and sets in depth.",
        modifiedDate: "2023-11-25",
        difficulty: "Beginner",
        category: "Java",
        prerequisite: "None",
        order: 6,
        isViewed: false
      },
      {
        chapterID: 100014,
        chapterSlug: "python-functions-deep-dive",
        roadmapID: 100002,
        title: "Functions Deep Dive",
        description: "Master Python functions, including scope, arguments, recursion, and best practices.",
        modifiedDate: "2023-11-28",
        difficulty: "Intermediate",
        category: "Java",
        prerequisite: "None",
        order: 7,
        isViewed: false
      },
      {
        chapterID: 100015,
        chapterSlug: "dom-manipulation",
        roadmapID: 100003,
        title: "DOM Manipulation",
        description: "Learn how JavaScript interacts with the Document Object Model (DOM).",
        modifiedDate: "2023-08-25",
        difficulty: "Beginner",
        category: "JavaScript",
        prerequisite: "None",
        order: 1,
        isViewed: false
      },
      {
        chapterID: 100016,
        chapterSlug: "javascript-es6-features",
        roadmapID: 100003,
        title: "ES6 Modern JavaScript Features",
        description: "Learn ES6 features including let/const, arrow functions, classes, and modules.",
        modifiedDate: "2023-09-10",
        difficulty: "Advanced",
        category: "JavaScript",
        prerequisite: "None",
        order: 2,
        isViewed: false
      },
      {
        chapterID: 100017,
        chapterSlug: "react-hooks-basics",
        roadmapID: 100004,
        title: "React Hooks Basics",
        description: "Learn essential React hooks such as useState and useEffect.",
        modifiedDate: "2023-10-12",
        difficulty: "Intermediate",
        category: "React",
        prerequisite: "None",
        order: 1,
        isViewed: false
      },
      {
        chapterID: 100018,
        chapterSlug: "react-component-lifecycle",
        roadmapID: 100004,
        title: "Component Lifecycle",
        description: "Understand how React components render and update throughout their lifecycle.",
        modifiedDate: "2023-10-20",
        difficulty: "Intermediate",
        category: "React",
        prerequisite: "None",
        order: 2,
        isViewed: false
      }
];

export const linksData: LinkCardProps[] = [
  {
    nodeID: 100001,
    chapterID: 100004,
    title: "Error Handling and Perception",
    modifiedDate: "2023-11-20",
    order: 1,
    link: "https://www.geeksforgeeks.org/java/exceptions-in-java/",
    isViewed: true
  },
  {
    nodeID: 100002,
    chapterID: 100011,
    title: "Java Stream API Guide",
    modifiedDate: "2023-11-22",
    order: 1,
    link: "https://www.baeldung.com/java-8-streams",
    isViewed: false
  },
  {
    nodeID: 100003,
    chapterID: 100012,
    title: "Java Lambda Expressions Tutorial",
    modifiedDate: "2023-11-22",
    order: 2,
    link: "https://www.geeksforgeeks.org/lambda-expressions-java-8/",
    isViewed: false
  },
  {
    nodeID: 100004,
    chapterID: 100013,
    title: "Python Data Structures Overview",
    modifiedDate: "2023-11-30",
    order: 1,
    link: "https://docs.python.org/3/tutorial/datastructures.html",
    isViewed: false
  },
  {
    nodeID: 100005,
    chapterID: 100014,
    title: "Python Functions Explained",
    modifiedDate: "2023-12-01",
    order: 2,
    link: "https://realpython.com/defining-your-own-python-function/",
    isViewed: false
  },
  {
    nodeID: 100006,
    chapterID: 100015,
    title: "DOM Manipulation Basics",
    modifiedDate: "2023-08-30",
    order: 1,
    link: "https://www.w3schools.com/js/js_htmldom.asp",
    isViewed: false
  },
  {
    nodeID: 100007,
    chapterID: 100016,
    title: "ES6 Features Overview",
    modifiedDate: "2023-09-12",
    order: 2,
    link: "https://www.javascripttutorial.net/es6/",
    isViewed: false
  },
  {
    nodeID: 100008,
    chapterID: 100017,
    title: "React Hooks Documentation",
    modifiedDate: "2023-10-15",
    order: 1,
    link: "https://react.dev/reference/react",
    isViewed: false
  },
  {
    nodeID: 100009,
    chapterID: 100018,
    title: "React Lifecycle Patterns",
    modifiedDate: "2023-10-25",
    order: 2,
    link: "https://blog.logrocket.com/understanding-react-component-lifecycle-methods/",
    isViewed: false
  }

]